# -*- coding: utf-8 -*-
"""Q5_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19fLBYgrxvEcH2qfm0URlFaLuEUyLMibB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from preprocessing.polynomial_features import PolynomialFeatures
from linearRegression.linear_regression import LinearRegression
import os.path
from os import path
import seaborn as sns

if not path.exists('Plots/Question5/'):
    os.makedirs('Plots/Question5/')

# TODO : Write here

np.random.seed(42)  #Setting seed for reproducibility

plot_details = {'N':list(), 'D':list(), 'T':list()}

N_range = [i for i in range(200,800,50)]
degree = [1,3,5,7,9]

for N in N_range:
    x = np.array([i*np.pi/180 for i in range(60,60+4*N,4)])
    y = 3*x + 8 + np.random.normal(0,3,len(x))

    for d in degree:
        poly = PolynomialFeatures(d, False)
        X = poly.transform(np.transpose([x]))
        LR = LinearRegression(True)
        LR.fit_normal_equations(pd.DataFrame(data=X), pd.Series(y))
        plot_details['N'].append(N)
        plot_details['D'].append(d)
        plot_details['T'].append(np.linalg.norm(LR.coef_))

labels = np.array(plot_details['T'])
labels = labels.reshape((len(N_range),len(degree)))

df = pd.DataFrame(data=plot_details)
heatmap1_data = pd.pivot_table(df, values='T', index=['N'], columns='D')
sns.heatmap(heatmap1_data, cmap="YlOrRd", annot=labels)
plt.title("Magnitude of theta with varying degree and number of training samples")
plt.savefig("Plots/Question5/fig.png")
plt.close()